/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Button: typeof import('./components/button/Button.vue')['default']
    ButtonDefine: typeof import('./components/button/ButtonDefine.vue')['default']
    ButtonSetup: typeof import('./components/button/ButtonSetup.vue')['default']
    ButtonSetupType: typeof import('./components/button/ButtonSetupType.vue')['default']
    ButtonTest: typeof import('./components/button/ButtonTest.vue')['default']
    MyComponent: typeof import('./components/ui/MyComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
